#SPDX-License-Identifier: MIT-0
---
# tasks file for installHttpApache
- name:  Install apache httpd to remote
  ansible.builtin.apt:
    name: "{{ application }}"
    state: present
    update_cache: yes
- name: Copy file with owner and permission
  ansible.builtin.copy:
    src: index.html
    dest: /var/www/html
    owner: root
    group: root
    mode: '0644' 