---
- hosts: all
  become: true
  tasks:
    - name: Print all the gathered ansible_facts
      ansible.builtin.debug: 
      var: ansible_facts
  tasks:
    - name: Shutdown ubuntu instances only
      ansible.builtin.command: /sbin/shutdown -t now
      when:
       ansible_facts['os_family'] == "Debian"
