---
- name: Install and Start nginx
  hosts: webservers
  become: true

  tasks:
    - name: Install nginx
     #We can do in different ways of installing using distrubution manager and also shell
     #shell: apt install nginx
      apt:
        name: nginx
        state: present

    - name: Start nginx
      # Same like install here also we can use shell and also there is a syntax to use with keyword service.
      # shell: systemctl start nginx
      service:
        name: nginx
        state: started
